#!/bin/bash

test -e "$1" || exit
proto=$1

proto_name=$(echo $proto | sed -e 's/\.proto$//g')
echo "proto_name: $proto_name"

service=$(grep service $proto | awk '{print $2}')
server_filename="$(echo $service | tr '[:upper:]' '[:lower:]'})_server.py"
client_filename="$(echo $service | tr '[:upper:]' '[:lower:]'})_client.py"
echo "service: $service"
echo "server_filename: $server_filename"
echo "client_filename: $client_filename"

cp ../utils/template_server.py ./$server_filename
sed -i "s/XXX/$service/g" $server_filename

cp ../utils/template_client.py ./$client_filename
sed -i "s/XXX/$service/g" $client_filename
